### ISSUE TITLE
[Video Streaming] Videos stream briefly, then stop completely

### ISSUE THREAD

**Issue by cmhnk** [rubyforgood/terrastories#1]
In addition to fixing this, let's add the ability to browse through the video (i.e., click through different points in time).

https://stackoverflow.com/questions/42737870/html5-video-in-rails-app-not-fully-watchable

**Comment by albertchae** [comment]
I noticed that the link provided by rails for a video, e.g.

`http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaDAzYW1kYWNEZzJZWFIwWm1SMlVWRkZORW8wTW5KWlMzTUdPZ1pGVkE9PSIsImV4cCI6IjIwMTktMDMtMzFUMTg6NTU6NDkuMjkwWiIsInB1ciI6ImJsb2Jfa2V5In19--48f45c77e58a6d5943e00ad9967bb1ff1b0b517e/JansoSedney.5.mp4?content_type=video%2Fmp4&disposition=inline%3B+filename%3D%22JansoSedney.5.mp4%22%3B+filename%2A%3DUTF-8%27%27JansoSedney.5.mp4`

If I download this to my computer and play it, it'll stop at the same point it's stopping in the web browser. I am trying to figure out if this is because of ActiveStorage or something with nginx

**Comment by albertchae** [comment]
https://github.com/rubyforgood/terrastories/pull/49 fixes the playback stopping, looking into the seeking issue now

**Comment by albertchae** [comment]
https://github.com/rubyforgood/terrastories/pull/63 fixes seeking. Closing issue
