### ISSUE TITLE
[CSV Data Importer] Handle diacritics / special characters

### ISSUE THREAD

**Issue by cmhnk** [rubyforgood/terrastories#10]
Currently, the importer in Administrate does not work when uploading a CSV with special characters such as á or ã. We should fix that because many languages use these kind of special characters.

Side note: some communities use characters like ō that are also not savable in CSV format. Perhaps there is a way to upload a different file format which does permit usage of such characters.

**Comment by rudokemper** [comment]
An example of a string that the CSV importer doesn't like: Elewōka Waurá

The standard accent á breaks the importer, and actually, the ō doesn't save in CSV format to begin with.

**Comment by albertchae** [comment]
Worked through this with @rudokemper. The CSV upload works as long as the conversion from Excel to CSV keeps the UTF-8 encoding.

* If the file is already an .xlsx, go to Google Sheets and File->Import from the menu. Then import the file.
* Otherwise create the file directly in Google Sheets. Make sure the file has a row for headers.
* Go to File->Download As-> Comma Separated Values, and save the file to your machine.
* This CSV should be properly encoded as UTF-8. It's best to verify this with Notepad++ instead of Excel if you are on a Windows machine.
