### ISSUE TITLE
[UI] Fix the height of story cards to encompass vertical size videos

### ISSUE THREAD

**Issue by rudokemper** [rubyforgood/terrastories#17]
Currently, the story cards don't adjust to fit the full height of a vertical video. (We have been working with horizontal video formats up until now.)

![image](https://user-images.githubusercontent.com/31662219/55279281-1f1c3f00-52d4-11e9-8d24-ef3efa6a4daa.png)

**Comment by gkop** [comment]
I'm going to take a stab at this!

**Comment by gkop** [comment]
I made a PR for this ^. Note it's not just vertical videos, but any video that's not horizontal enough - eg. square videos also have broken layout on master right now.

**Comment by gkop** [comment]
It just occurred to me now - but since we control the video source, a future enhancement would be to record the video dimensions in the database at the time the user uploads it. That would be nicer. I think activestorage and other rails gems helps with extracting the dimensions, and it's a good thing to do in general. I did check and currently we are not extracting the dimensions, so we need to do that first before we can use them to better address this bug.

**Comment by baweaver** [comment]
If you want to make a ticket addressing that feel free. I think the immediate priority on video are thumbnails, ActiveStorage cropping, and fullscreen crashing.
