### ISSUE TITLE
[Maps] Map content not showing up on TileServer GL

### ISSUE THREAD

**Issue by cmhnk** [rubyforgood/terrastories#4]
For the first Terrastories project built for the Matawai, the map content drawn by TileServer GL showed up just fine. But when building Terrastories with shapefiles in different geographies or scales, TileServer GL seems to have some issues.

For the Ulupuene project, all the layers are successfully drawn. However, for a number of the point and label layers, only a selection of the content shows up: https://github.com/rudokemper/terrastories-ulupuene

This branch being developed for Terrastories as a SaaS has just generic world countries and cities point content, When running this branch, only the city points and labels show up. Here, too, it is only a selection of the cities points. More points show up when you zoom in more. The polygons are never drawn, but by going to http://localhost:3000/tiles/data/basic.json we can confirm that tileserver does have access to the map tiles as built by tilebuilder.

**Comment by rudokemper** [comment]
I figured out why the shapefiles weren't showing up: it had to do with the projection of the shapefiles. So that addresses the third paragraph in this Issue.

But there is still some finetuning of Tileserver GL that remains.

![Capture1](https://user-images.githubusercontent.com/31662219/55282781-c3b87400-5308-11e9-9f93-d5d2535dfb49.PNG)

This is what a map styled in Mapbox Studio looks like. No zoom limits on the point shapefile.

![Capture2](https://user-images.githubusercontent.com/31662219/55282789-d632ad80-5308-11e9-84de-fa63128644c9.PNG)

But on Terrastories right now, no points or labels show up at the same zoom level.

![Capture3](https://user-images.githubusercontent.com/31662219/55282796-e21e6f80-5308-11e9-8fab-eba54cfff370.PNG)

When you start to zoom in, they show up, but pretty selectively. There are more points in this view, like Pittsburgh and Columbus, that are not showing until I zoom in more.
